# Generated by Django 5.1 on 2024-08-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_recipe_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_recipe',
            name='recipe_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_recipe',
            name='recipe',
            field=models.TextField(),
        ),
    ]
