# Generated by Django 5.1 on 2024-08-26 16:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_user_recipe_recipe_name_alter_user_recipe_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_recipe',
            name='recipe',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
