# Generated by Django 5.1 on 2024-08-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_user_recipe_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_recipe',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
