# Generated by Django 5.1 on 2024-08-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_user_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_recipe',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='Recipe imgs'),
        ),
        migrations.AlterField(
            model_name='user_recipe',
            name='recipe',
            field=models.TextField(),
        ),
    ]
